@apiHostAddress = {{apiBaseUrl}}

GET {{apiHostAddress}}/weatherforecast/
Accept: application/json

###
GET {{apiHostAddress}}/health
Accept: application/json

###
# Ejemplo con headers de identidad requeridos por varios endpoints de negocio.
GET {{apiHostAddress}}/api/rrhh/justificaciones
X-User-Id: {{userId}}
X-User-Role: {{userRole}}
Accept: application/json

###
