USE INTEGRA_CNP

IF EXISTS (SELECT 1 FROM sys.views WHERE name = 'V_JUSTIFICACIONES_DETALLE' AND type = 'V')
    DROP VIEW dbo.V_JUSTIFICACIONES_DETALLE;
GO

CREATE VIEW dbo.V_JUSTIFICACIONES_DETALLE
AS
SELECT
    ENC.NUM_JUSTIFICACION AS NUM_JUSTIFICACION,
    DET.COD_LINEA AS COD_LINEA,
    DET.FEC_JUSTIFICACION AS FEC_JUSTIFICACION,
    LTRIM (
        RTRIM (
            ISNULL (USR_SOL.DES_NOMBRE, '') + ' ' + ISNULL (USR_SOL.DES_APELLIDO1, '') + ' ' + ISNULL (USR_SOL.DES_APELLIDO2, '')
        )
    ) AS SOLICITANTE,
    LTRIM (
        RTRIM (
            ISNULL (USR_AUT.DES_NOMBRE, '') + ' ' + ISNULL (USR_AUT.DES_APELLIDO1, '') + ' ' + ISNULL (USR_AUT.DES_APELLIDO2, '')
        )
    ) AS AUTORIZA,
    LTRIM (
        RTRIM (
            ISNULL (USR_APR.DES_NOMBRE, '') + ' ' + ISNULL (USR_APR.DES_APELLIDO1, '') + ' ' + ISNULL (USR_APR.DES_APELLIDO2, '')
        )
    ) AS APRUEBA,
    ENC.FEC_CONFECCION AS FEC_CONFECCION,
    ENC.DES_JUSTIFICACION AS DES_JUSTIFICACION,
    ENC.DES_OBSERVACIONES AS DES_OBSERVACIONES,
    CEN.DES_CENTRO AS CENTRO,
    ENC.COD_ESTADO AS COD_ESTADO,
    ENC.FEC_AUTORIZACION AS FEC_AUTORIZACION,
    ENC.FEC_APROBACION AS FEC_APROBACION,
    ENC.FEC_ANULACION AS FEC_ANULACION,
    ENC.COD_ANULA AS COD_ANULA,
    ENC.DES_MOTIVO AS DES_MOTIVO,
    DET.IND_CONCEPTO AS IND_CONCEPTO
FROM
    dbo.RH_JUSTIFICACIONES_ENC AS ENC
    INNER JOIN dbo.RH_JUSTIFICACIONES_DET AS DET ON DET.NUM_JUSTIFICACION = ENC.NUM_JUSTIFICACION
    LEFT JOIN dbo.RH_FUNCIONARIOS AS USR_SOL ON USR_SOL.COD_FUNCIONARIO = ENC.COD_SOLICITANTE
    LEFT JOIN dbo.RH_FUNCIONARIOS AS USR_AUT ON USR_AUT.COD_FUNCIONARIO = ENC.COD_AUTORIZA
    LEFT JOIN dbo.RH_FUNCIONARIOS AS USR_APR ON USR_APR.COD_FUNCIONARIO = ENC.COD_APRUEBA
    LEFT JOIN dbo.RH_CENTROS_COSTO AS CEN ON CEN.COD_CENTRO = ENC.COD_CENTRO;
GO

-- Verificación
EXEC sp_helptext 'dbo.V_JUSTIFICACIONES_DETALLE';