USE INTEGRA_CNP
GO

CREATE VIEW VW_RH_JUSTIFICACIONES
AS
SELECT
    ENC.NUM_JUSTIFICACION AS NUM_JUSTIFICACION,
    DET.COD_LINEA AS COD_LINEA,
    DET.FEC_JUSTIFICACION AS FEC_JUSTIFICACION,
    USR_SOL.DES_NOMBRE + ' ' + USR_SOL.DES_APELLIDO1 + ' ' + USR_SOL.DES_APELLIDO2 AS SOLICITANTE,
    USR_AUT.DES_NOMBRE + ' ' + USR_AUT.DES_APELLIDO1 + ' ' + USR_AUT.DES_APELLIDO2 AS AUTORIZA,
    USR_AUT.DES_NOMBRE + ' ' + USR_AUT.DES_APELLIDO1 + ' ' + USR_AUT.DES_APELLIDO2 AS APRUEBA,
    ENC.FEC_CONFECCION AS FEC_CONFECCION,
    ENC.DES_JUSTIFICACION AS DES_JUSTIFICACION,
    CEN.DES_CENTRO AS CENTRO,
    ENC.COD_ESTADO AS COD_ESTADO,
    ENC.FEC_AUTORIZACION AS FEC_AUTORIZACION,
    ENC.FEC_APROBACION AS FEC_APROBACION,
    ENC.FEC_ANULACION AS FEC_ANULACION,
    ENC.COD_ANULA AS COD_ANULA,
    ENC.DES_MOTIVO AS DES_MOTIVO,
    ENC.DES_OBSERVACIONES AS DES_OBSERVACIONES,
    DET.IND_CONCEPTO AS IND_CONCEPTO
FROM
    SIFCNP.dbo.RH_JUSTIFICACIONES_ENC ENC
    JOIN SIFCNP.dbo.RH_JUSTIFICACIONES_DET DET 
        ON ENC.NUM_JUSTIFICACION = DET.NUM_JUSTIFICACION
    JOIN SIFCNP.dbo.RH_FUNCIONARIOS USR_SOL 
        ON ENC.COD_SOLICITANTE = USR_SOL.COD_FUNCIONARIO
    JOIN SIFCNP.dbo.RH_FUNCIONARIOS USR_AUT 
        ON ENC.COD_AUTORIZA = USR_AUT.COD_FUNCIONARIO
    JOIN SIFCNP.dbo.RH_FUNCIONARIOS USR_APR 
        ON ENC.COD_AUTORIZA = USR_APR.COD_FUNCIONARIO
    JOIN SIFCNP.dbo.RH_CENTROS_COSTO CEN 
        ON ENC.COD_CENTRO = CEN.COD_CENTRO
GO